# Generated by Django 4.2.7 on 2023-11-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0001_initial'),
        ('character', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discordID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='discordlogin.discorduser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='character',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='character.character'),
        ),
    ]
