# Generated by Django 4.2.7 on 2023-11-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_transaction_discordid_alter_transaction_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='discordID',
            new_name='discord',
        ),
    ]
