# Generated by Django 4.2.7 on 2023-11-15 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        ('discordlogin', '0001_initial'),
        ('marketplace', '0003_rename_discordid_transaction_discord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordlogin.discorduser'),
        ),
    ]
