# Generated by Django 4.2.7 on 2023-11-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_transaction_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='discord',
        ),
    ]
