# Generated by Django 4.2.7 on 2023-11-09 04:58

from django.db import migrations, models
import django.db.models.deletion
import npc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weapon', '0001_initial'),
        ('gear', '0001_initial'),
        ('power', '0001_initial'),
        ('cyberware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_gear', to='gear.gear')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('race', models.CharField(choices=[('android', 'Android'), ('angler', 'Angler'), ('anklebiter', 'Anklebiter'), ('apex', 'A-Pex'), ('aquarian', 'Aquarian'), ('aurax', 'Aurax'), ('avion', 'Avion'), ('behemoth', 'Behemoth'), ('bloodwing', 'Bloodwig'), ('boomer', 'Boomer'), ('colemata', 'Colemata'), ('construct', 'Construct'), ('deader', 'Deader'), ('deathcrawler', 'Death Crawler (Swarm)'), ('drake', 'Drake'), ('dwarf', 'Dwarf'), ('elf', 'Elf'), ('floran', 'Floran'), ('grazer', 'Grazer'), ('halfelve', 'Half-Elve'), ('halffolk', 'Half-Folk'), ('human', 'Human'), ('hunter', 'Hunter'), ('insectoid', 'Insectoid'), ('kalian', 'Kalian'), ('krok', 'Krok'), ('krokgiant', 'Krok, Giant'), ('lightningdarter', 'Lightning Darter (Swarm)'), ('lacerauns', 'Lacerauns'), ('mauler', 'Mauler'), ('rakashan', 'Rakashan'), ('ravager', 'Ravager'), ('robot', 'Robot'), ('sailfin', 'Sailfin'), ('saurian', 'Saurian'), ('scrat', 'Scrat'), ('scuteboar', 'Scute Boar'), ('serran', 'Serran'), ('scylla', 'Scylla'), ('scyllagiant', 'Scylla, Giant'), ('sirencreeper', 'Siren Creeper'), ('spitter', 'Spitter'), ('yeti', 'Yeti')], max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('charisma', models.IntegerField(default=0)),
                ('pace', models.IntegerField(default=0)),
                ('parry', models.IntegerField(default=0)),
                ('toughness', models.IntegerField(default=0)),
                ('attributes', models.JSONField()),
                ('skills', models.JSONField()),
                ('hindrances', models.TextField(blank=True)),
                ('edges', models.TextField(blank=True)),
                ('damage', models.JSONField(default=npc.models.default_damage)),
                ('ammo', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('cyberware', models.ManyToManyField(blank=True, to='cyberware.cyberware')),
                ('gear', models.ManyToManyField(blank=True, through='npc.GearQuantity', to='gear.gear')),
                ('powers', models.ManyToManyField(blank=True, to='power.power')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc.npc')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_weapon', to='weapon.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='weapons',
            field=models.ManyToManyField(blank=True, through='npc.WeaponQuantity', to='weapon.weapon'),
        ),
        migrations.AddField(
            model_name='gearquantity',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc.npc'),
        ),
    ]
