# Generated by Django 4.2.7 on 2023-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='faction',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('neutral', 'Neutral'), ('friendly', 'Friendly'), ('enemy', 'Enemy')], default='unknown', max_length=255),
        ),
    ]
