# Generated by Django 4.2.7 on 2023-11-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('range', models.CharField(blank=True, max_length=255)),
                ('damage', models.CharField(max_length=255)),
                ('rof', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('min_str', models.CharField(blank=True, max_length=255)),
                ('wt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
