# Generated by Django 4.2.7 on 2023-11-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pp', models.CharField(max_length=255)),
                ('range', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('effect', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
