# Generated by Django 4.2.7 on 2023-11-09 04:55

import discordlogin.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('global_name', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('mfa_enabled', models.BooleanField()),
                ('locale', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('verified', models.BooleanField()),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_gm', models.BooleanField(default=False)),
                ('is_player', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('objects', discordlogin.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
