# Generated by Django 4.2.7 on 2023-11-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
