# Generated by Django 4.2.7 on 2023-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
        ('npc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('characters', models.ManyToManyField(blank=True, to='character.character')),
                ('npcs', models.ManyToManyField(blank=True, to='npc.npc')),
            ],
        ),
    ]
